site_name: QuTech - Data & Software
site_description: 'Information for researchers at QuTech on Data & Software Development'
site_author: 'QuTech'
docs_dir: docs/
repo_name: 'QuTech-Delft/data-and-software-info'
repo_url: 'https://github.com/QuTech-Delft/data-and-software-info'
nav:
    - Home: index.md
    - Data: 
      - data/index.md
    - Software: 
      - software/index.md
      - "FAIR Software (QSSM 2)": software/FAIR.md
      - "Software Testing": software/testing.md
      - "Version Control Systems": software/vcs.md

theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'amber'
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
